### ISSUE TITLE
Generating SDP graph

### ISSUE THREAD

**Issue by Suneal** [L-Zhe/SDISS#1]
Hi,
How can I create the SDP graph for my dataset?

**Comment by L-Zhe** [comment]
We provide the SDP graph for Newsela, WikiSmall and WikiLarge, and you can download them in [here](https://github.com/L-Zhe/SDISS/releases). If you want to train SDISS with your own dataset, you can employ some SDP parser models to get the corresponding  SDP graph.

We leverage the SDP parser model in this [paper](https://www.aclweb.org/anthology/K19-2016/), you can contact the authors to get the parser.
